stages:
  - build

rust:build:
  stage: build
  image:
    name: rust:1.91-trixie
    entrypoint: ["/usr/bin/env"]
  variables:
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
  before_script:
    - apt update
    - apt install -y gcc-aarch64-linux-gnu protobuf-compiler
    - rustup target add aarch64-unknown-linux-gnu
  script:
    - cargo build --release --no-default-features --features sources-journald,sources-docker_logs,sources-nats,transforms-remap,sinks-nats,sinks-loki
    - cargo build --release --no-default-features --target aarch64-unknown-linux-gnu --features sources-journald,sources-docker_logs,sources-nats,transforms-remap,sinks-nats,sinks-loki
  artifacts:
    paths:
      - target/release/vector
      - target/aarch64-unknown-linux-gnu/release/vector
